- menu_name: ""

- name: "Contacto"
  url: "/contacto/"
  class: "services-contact"
  title: "Contacto"

# - name: "RSS"
#   url: "/feed.xml"
#   class: "rss-link"
#   title: "Subscribe to RSS"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  class: "sitemap-link"
  title: "Mapa del sitio para google"
